name: 'CI'

on:
  push:
    branches:
      - master
      - feat-github-actions
  pull_request_target: {}

env:
  GCLOUD_VERSION: "392.0.0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        go_version:
          - ~1.11
          - ~1.12
          - ~1.16
    permissions:
      contents: read
    env:
      GO111MODULE: "on"
      DATASTORE_EMULATOR_HOST: "localhost:8081"
      DATASTORE_PROJECT_ID:    "unittest"
      GOOGLE_CLOUD_PROJECT:    "unittest"
    steps:
      - uses: actions/checkout@v3
        with:
          # pull_request_target の場合PRのhead(場合によってはvulnerable)、そうじゃなければcontextのsha
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Cache go dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-go-cache-r1-${{ matrix.go_version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          path: |-
            ~/go/pkg/mod
      - name: Prepare dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |-
          go mod download
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: ${{ env.GCLOUD_VERSION }}
          project_id: ${{ env.DATASTORE_PROJECT_ID }}
          install_components: "beta,cloud-datastore-emulator,app-engine-go"
      - name: Spinup Datastore Emulator
        run: |-
          gcloud beta emulators datastore start --host-port=0.0.0.0:8081 --no-store-on-disk --consistency=1.0 &
          curl http://localhost:8081 --silent --retry 30 --retry-connrefused --retry-delay 1
      - name: Run tests
        run: |-
          go test -v ./...
